name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: RAD-tools version
      description: What version of our software are you running?
      placeholder: ex. 0.7.15
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python version
      description: What version of Python areyou using our software with?
      placeholder: ex. 3.11.4
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What operating system are you using?
      options:
        - MacOS (ARM)
        - MacOS (Intel)
        - Linux (Ubuntu)
        - Windows
        - Linux (Other)
    validations:
      required: true
